### PR TITLE
feat: consolidate params' serialization type in one place

### LINKED ISSUE #7: Consolidate params' serialization type in one place
Current we add serialization type to each parameter individually like this:
```json
{
  "name": "foo",
  "params": [
    {
      "name": "a",
      "serialization_type": "json",
      "type_schema": {}
    },
    {
      "name": "b",
      "serialization_type": "json",
      "type_schema": {}
    }
  ]
}
```

This is redundant as there should always be one uniform serialization format for all parameters. There are a few ways of how this could look.

#### Top-level function key
```json
{
  "name": "foo",
  "params_serialization_type": "json",
  "params": [
    {
      "name": "a",
      "type_schema": {}
    },
    {
      "name": "b",
      "type_schema": {}
    }
  ]
}
```

Not sure if I like this one as it is unclear that the `params` internal structure depends on another sibling field.

#### Rename `params` to `params_json`/`params_borsh`
```json
{
  "name": "foo",
  "params_json": [
    {
      "name": "a",
      "type_schema": {}
    },
    {
      "name": "b",
      "type_schema": {}
    }
  ]
}
```

Could work, but this is kind of a weird pattern; I imagine it would be difficult to describe in a lot of languages

#### Create a two-level struct
```json
{
  "name": "foo",
  "params": {
    "serialization_type": "json",
    "args": [
      {
        "name": "a",
        "type_schema": {}
      },
      {
        "name": "b",
        "type_schema": {}
      }
    ]
  }
}
```

Probably the most precise one, but also a bit verbose.

### PR DESCRIPTION
**Pull request by itegulov**
Fixes #7 

How to represent this is a bit opinionated, but I feel like this is the least ambiguous way to do it.

### CODE REVIEW

**Review by austinabell — APPROVED** [review]
I think this makes sense!

**Review by miraclx — APPROVED** [review]
lgtm 👍🏽

**Comment by austinabell** [comment]
Should the ABI version be bumped for this? 0.2? Or coming in a separate PR?

**Comment by itegulov** [comment]
> Should the ABI version be bumped for this? 0.2? Or coming in a separate PR?

Yeah, will bump in a separate PR once both open PRs are in

**Pull request merged**
